Model added
Product model added.
Data folder added for storing json data.

error: products.length is not defined
***Issue in fetchAll because of asynchronous structure***